### PR TITLE
Fix multibranch pr triggering

### PR DESCRIPTION
**Pull request by michallaskowski**
Marking as Work In Progress since unit tests are passing, but I am new to Atlassian plugins I have yet to configure my local Bitbucket Server to test it out. If any anyone can do it too, I would be grateful.

It should solve problems with jobs for PRs not being triggered correctly for multibranch pipelines.
As stated in #109 , the plugin should scan the reposistory for any PR related trigger, and trigger PR jobs directly only from a manual trigger (though in another PR it is possible it will be needed to trigger scan if somehow the job doesn't exist yet)

### CODE REVIEW

**Comment by a-hacker** [comment]
Hi @michallaskowski, thanks for the contribution! I started putting together some developer docs in our [wiki](https://github.com/KyleLNicholls/parameterized-builds/wiki/Developer-Guide) that should help you get a testing environment set up. I'll also give it a test too when I get a good chance.

I think this PR is a step in the right direction. However, multibranch pipelines are a bit tricky because of the various behaviors that can be set. All the following are available behaviors:
- Discover all branches (subjobs are created as branch name)
- Discover only branches filed as PRs (subjobs are created as branch name)
- Discover only branches __not__ filed as PRs (subjobs are created as branch name)
- Discover PRs and use the current revision (subjobs are created as PR-$PRID?)
- Discover PRs and use a merged revision (subjobs are created as PR-$PRID?)
- Discover PRs and use both current revision and a merged revision (???)
- Discover tags (subjobs are created as tag name?)

Off the top of my head I don't remember exactly what the PR and tag behaviors call the subjobs but they are distinct from the branch strategy. 

Ultimately, what we need is a way for users to define which strategies they are using and trigger things appropriately since there is no "one size fits all" approach to how jobs should be triggered. Because of this, I would like to preserve the current functionality of the plugin when a user indicates they are not trying to discover PRs and have the effects of the change you made when they are discovering PRs.

**Comment by michallaskowski** [comment]
Hey.
I had Bitbucket already running with atlas-run, and Jenkins in docker cause I was doing some toher Jenkins related PRs. But I am having trouble setting up Bitbucket address in Jenkins system config - I set them to a gateway address I am getting when using docker inspect - the standard one I think
http://172.17.0.1:7990 , or http://172.17.0.1:7990/bitbucket (neither works)
When setting up a multibranch job it can't find projects in BitBucket. Any ideas, could you maybe cover that in the wiki?

About multibranch behaviors - yes, there are different ones, but I don't see yet how they could affect how the plugin will trigger Jenkins.
- Anytime there is a new PR, scan needs to happen, no matter if it will be merged to target or not. Jenkins needs to find this PR with scan
- the same goes for new commits in PRs, closing, declining, merging - the state of PR changed, scan needs to happen
- manual trigger - here I am working on an assumption that scan happened already, so PR is listed (if not, this could be handle in another PR, need to handle 404 response). Then it will trigger an existing subjob.
- I don't know how tags are represented in multibranch, but anyway I think this is again a topic for another pull request. This one I would limit to handling PR triggers only.

**Comment by a-hacker** [comment]
I may have given some poor advice there for the multibranch pipeline support as I was mostly going off of memory. [This stackoverflow article](https://stackoverflow.com/questions/36728994/how-to-access-webserver-running-on-localhost-from-a-docker-container-on-a-networ) should be of assistance. I'll get the docs updated with better info.

One big thing to keep in mind is that scans cannot pass parameters from Bitbucket. Only a build can. To that degree, builds provide more value but a scan must happen first. Because of that and the various behaviors multibranch pipelines support it does matter what we trigger and how. Addressing your bullet-points:
- __Anytime there is a new PR, scan needs to happen, no matter if it will be merged to target or not. Jenkins needs to find this PR with scan__ This isn't necessarily true. If a job discovers all branches then a scan on PR events won't actually do anything. However, if you want to pass PR-related info in the params to a build, using the build url will cause a new build with those params. In all fairness, most of that info is available through `env.CHANGE_ID, env.CHANGE_AUTHOR, etc.` I could be persuaded that scans are the way to go but this plugin is _Parameterized Builds_ for Jenkins so I've tried to uphold the parameterized portion of that.

- __the same goes for new commits in PRs, closing, declining, merging - the state of PR changed, scan needs to happen__ New commits actually registers as a push event whether a PR is open or not so that is already covered. As for the other PR events, same example from prior point still applies.

- __manual trigger - here I am working on an assumption that scan happened already, so PR is listed (if not, this could be handle in another PR, need to handle 404 response). Then it will trigger an existing subjob.__ This is really the part I'm concerned about. It's safe to assume that a scan has already happened but the name of the subjob is trickier. This change assumes that if a manual build is triggered from a PR page, there will be a subjob called PR-$PRID. This is never a guarantee and is very dependent on the specific pipeline configuration. If I was unclear before that my hesitation is in this aspect of the PR I apologize but this will cause serious regressions for some users.

 - __I don't know how tags are represented in multibranch, but anyway I think this is again a topic for another pull request. This one I would limit to handling PR triggers only.__ I absolutely agree and I did not mean to imply any scope creep. I only included the info about tags to demonstrate how the actual subjob names and events that cause builds vary dramatically depending on the configuration settings of the multibranch pipeline.

**Comment by michallaskowski** [comment]
Thanks for the clarification :)
I was able to setup Jenkins and BitBucket after few docker changes, so maybe I will be able to help with wiki. I am working on macOS, started docker with `docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:latest` and then was able to address BitBucket with `http://host.docker.internal:7990/bitbucket` (a really new, shiny feature in latest Docker for Mac, afaik)

About your points:
- **Parameterized Builds for Jenkins so I've tried to uphold the parameterized portion of that** - true, somewhere in the back of my head I was just thinking about not using parameters for now, but you are totally right. But there is no way I can see right how to make it work. I am though 99% positive that there is a distinction between branch and PR in multibranch - having a branch scanned, and opening a PR will create a new job just for this PR - needs to happen because PRs could be handled differently, because we get all env variables related to pull requests. There is also a separate tab for pull requests in multibranch UI.
- **This change assumes that if a manual build is triggered from a PR page, there will be a subjob called PR-$PRID. This is never a guarantee and is very dependent on the specific pipeline configuration**  - I would need to find some better docs, but what I understand from https://wiki.jenkins.io/display/JENKINS/SCM+API+Plugin Version 2.2.4 is that `PR-` prefix is hardcoded (but may be wrong of course, please let me know, maybe it just works in our setup)

Ok, so the case is I really don't know how to make it so all the builds are parameterized, because scans aren't. Not sure if is possible, but 100% positive I would like to have multibranch pipelines supported anyway.
To justify it I will present our use case, because I feel I was not 100% clear why I believe this plugin would work for multibranch pipeline:
We are currently using this great plugin for standard pipeline jobs, and it is serving us well, but for various reasons we would like to have some jobs configured as multibranch.
Our use case is that some subjobs (branches) could be parametrized, like master - we could start a build that would build our app in some parameterized flavor and upload artifacts. The same could be said for long lived release branches - I guess we can live with that if first scan on them fails, and just second  push or manual trigger will work. Maybe we can come up with a better solution later.

Also we would like to be able to test Pull Requests with the same job - they will not be parameterized because there is no need to do - those subjobs are short lived, until we merge the PR. It is also not parameterized because we need to test every flavor of our app, in every aspect - there is just nothing that can be parameterized.

So our typical use case would be to:
- discover 'PRs and merge them to master'
- 'branches not filled as PRs' with whitelisted  'master release/* PR-*'

Let me know if that makes sense.

----------------

Anyway, while testing I found I need to do some changes in JS files to send info about pull request id when manually triggering from PR view, right now only a branch name is sent.

Some good and bad news - scanning works after opening the PR, but first subjob always fails. Retries (manual from plugin, or in Jenkins) pass. I believe this is related to: https://issues.jenkins-ci.org/browse/JENKINS-45997 - we open a PR, Jenkins scans the repo and tries to fetch, but refs are not yet updated and it fails to fetch from repo.
There is a workaround mentioned, to call `canMerge()` api endpoint, which will update refs, before notifying Jenkins.

Seems like more work that I anticipated, if you agree we want that change ;)

**Comment by michallaskowski** [comment]
Applied changes I mentioned in previous message. Let me know what you think. In my case, those changes would work great in my company, and we would love to adopt multibranch pipelines while keeping this plugin. I understand not all use cases are covered right now.

**Comment by James-Newman** [comment]
I can't find a way of testing this, but I'm so glad I found this being worked on.
Does it support also notifying bitbucket of the success/failure of the builds?
Does it support both pre-merge and post-merge testing?

**Comment by michallaskowski** [comment]
BitBucket branch source plugin handles notifications, not this plugin, no change there, it still works.
Triggers are staying the same - so opening a PR will trigger a scan and jenkins should pick up this new PR and build it.
Post merge - so if plugin is set to notify about ref changes, scan will also happen and it should pick changes on a changed branch.

**Comment by a-hacker** [comment]
@michallaskowski, thanks for the updates. I wasn't aware of the issue you linked and it's good that it has an easy enough fix.

Before I submit a full code review the issue with the manual trigger needs to be addressed. As you mentioned, your setup involves discovering branches not filled as PRs with some whitelisting and discovering PRs with post-merge refs. Therefore, when you create a PR, you lose the job for the branch and a new job named PR-$PRID is created. 

The code you've proposed works well with your setup but will break functionality for other users. Anyone who discovers all branches (and therefore retains jobs for a branch when a PR is created) and does not discover any PRs will not be able the trigger jobs from a pull request. The current iteration only supports users who discover all branches and I'm more than happy to see expanded functionality but it needs to be an actual expansion and not a shift from one setup to another.

What I propose as a solution is a way to specify what a user's configuration settings are when they create the trigger. For right now, that could just be another checkbox asking the user if they discover PRs. Some sort of selector would probably be better for the long-term though.

Thanks again for your work. It looks pretty solid and I'm glad to see work done on this feature.

**Comment by a-hacker** [comment]
Due to inactivity, I'm closing this PR.

**Pull request closed without merging**
