### PR TITLE
Fix duplicate calls when Build Token Root Plugin used

### PR DESCRIPTION
**Pull request by a-hacker**
As mentioned in #71, When Build Token Root Plugin is enabled, two builds will be triggered instead of one. This is due to the naive way the base url was being parsed from the jenkins rest url that triggers the job when trying to get the crumb. This PR fixes this by using the URL lib to rebuild the base url instead.

I have manually tested this with both Build Token Root Plugin enabled and disabled and both CSRF protection enabled and disabled. All cases behave as expected.

### CODE REVIEW

**Comment by sebbay** [comment]
@a-hacker : We are using your Plugin integrated in BitBucket-Server 4.14.4 and we are running into this issue with the duplicate calls. Can you please provide your fix in a branch based on Build 2.6.9?

**Comment by a-hacker** [comment]
@sebbay, we are no longer actively supporting bitbucket 4.X since the release of bitbucket 5. I can create the branch you asked for but I cannot release it on the Atlassian marketplace. You will need to convince @KyleLNicholls to do that or manually create a jar and upload it on your bitbucket instance.

If I do this though, I cannot promise to maintain that branch if any other issues arise.

**Comment by KyleLNicholls** [comment]
If you make the branch I'll release it

**Comment by sebbay** [comment]
Thank you!!! This would be great.

**Comment by a-hacker** [comment]
@KyleLNicholls, everything should be all set on the bitbucket4 branch

**Comment by KyleLNicholls** [comment]
Thanks
@sebbay released in v2.6.10

**Comment by sebbay** [comment]
Thanks!!!

**Pull request merged**
