### PR TITLE
Added $FROMCOMMIT variable

### PR DESCRIPTION
**Pull request by samifruit514**
In some cases, we need to know differences between 2 git commits that are not directly linked together.

For example, if I work locally and I do 8 commits in a row with different operations (modification, deletion, etc) and I push the branch, only the last commit ID is read and because of this, we are unable to find all the changed files since those last 8 commits.

With this PR, we can do a diff between the latest commit ($COMMIT) and the last commit before the push ($FROMCOMMIT) and that way we are sure to catch all the modifications.

### CODE REVIEW

**Comment by pascallap** [comment]
Wow this is exactly what we need!
With a proper git diff-filter we would be able to act properly on the changes.

**Comment by guylain** [comment]
I added $FROMCOMMIT on the PullRequest form of triggerFromPR method.

**Comment by a-hacker** [comment]
Is there a reason you didn't also add it to the AutomaticPullRequest form as well? I know it is not very simple but it feels like it should be included there too.

 I also tested out this PR with a manual build and it failed to populate the variable. Even though it doesn't make that much sense for manual builds, I don't like the idea of variables just not working unless explicitly mentioned. I'd recommend adding fromcommit to the BitbucketVariables in BuildResource.getJobs with the value being the same as commit.

**Comment by KyleLNicholls** [comment]
Conflicts need to be resolved

**Pull request closed without merging**
